#!/bin/bash

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
DOWNH=~/Downloads
DOWND=/home/docker/Downloads

touch "$XAUTH"
xauth nlist :0               \
    | sed -e 's/^..../ffff/' \
    | xauth -f "$XAUTH" nmerge -

docker run --rm -ti        \
    -e DISPLAY="$DISPLAY"  \
    -v "$XSOCK:$XSOCK"     \
    -v "$XAUTH:$XAUTH"     \
    -v "$DOWNH:$DOWND"     \
    -e "XAUTHORITY=$XAUTH" \
    firefox

rm "$XAUTH"
